### ISSUE TITLE
Cookies template

### ISSUE THREAD

**Issue by cuihantao** [pinguo-chexing/stock_discover#1]
您好！感谢开发这个包！

可够提供一份cookies.ext文件的样本格式？是否能更详细说明下哪个field是cookies呢？我在雪球网上看到xq_a_token, xq_r_token等。多谢！

**Comment by TsmileAssassin** [comment]
<img width="415" alt="cookie" src="https://user-images.githubusercontent.com/5343937/27077210-e268261c-5061-11e7-8600-a3e70e75fe7c.png">
你可以通过chrome在登陆雪球的情况下  开发者工具 查看雪球的请求的header，找到Cookie
